name: Flask App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Python (ensure to use a supported version like 3.10 or 3.11)
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Change to a supported version like 3.10 or 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Run Flask app in the background
      - name: Run Flask app in the background
        run: |
          nohup python main.py &
          sleep 10  # Allow some time for the Flask app to start

      # Run post-setup steps
      - name: Run tests or setup after Flask starts
        run: |
          # Your post-setup actions or tests go here
          echo "Flask app running, proceeding with next steps."
